"""Identity / sequence reset after a pgloader bulk load."""

from __future__ import annotations

from typing import Any

from shopifyseo.db.backend import Backend
from shopifyseo.db.identity import IDENTITY_COLUMNS, ResyncResult, ensure_identity

from .catalog import SKIP_IDENTITY_TABLES


def resync_cutover_identities(
    conn: Any,
    *,
    backend: Backend | None = None,
) -> list[ResyncResult]:
    """Add GENERATED BY DEFAULT AS IDENTITY where missing and setval to max+1.

    Discovers single-column integer PKs, always includes ``IDENTITY_COLUMNS``,
    and skips ``seo_change_events`` (task_id is copied, not sequenced).
    """
    from shopifyseo.db.helpers import table_exists
    from shopifyseo.db.identity import _discover_identity_tables

    if backend is None:
        backend = Backend.POSTGRES

    discovered = dict(_discover_identity_tables(conn))
    for table, column in IDENTITY_COLUMNS.items():
        if table_exists(conn, table):
            discovered[table] = column
    results: list[ResyncResult] = []
    for table, column in sorted(discovered.items()):
        if table in SKIP_IDENTITY_TABLES:
            results.append(
                ResyncResult(
                    table=table,
                    column=column,
                    error="skipped (not an independent identity)",
                )
            )
            continue
        results.append(ensure_identity(conn, table, column, backend=backend))
    return results
