"""Dual-backend test database helpers (PostgreSQL plan 7a).

``TEST_DATABASE_URL`` selects the backend for the shared fixtures in
``tests/conftest.py``:

- Unset / empty / non-postgres: SQLite temp file (today's smoke default).
- ``postgresql://`` or ``postgres://``: open via ``shopifyseo.db.get_connection``
  (same path as production ``connect()``), so session ``timezone=UTC`` and
  CURRENT_TIMESTAMP → naive UTC text from plan 6 still apply.

Plan 7b–d should migrate ``sqlite3.connect`` call sites onto ``testdb`` /
``db_conn`` rather than adding a second fixture stack.

Postgres ``testdb`` connections are adapted so leftover SQLite-shaped SQL in
tests and production DDL (`?` placeholders, ``executescript``, AUTOINCREMENT,
``INSERT OR IGNORE``, PRAGMA) still runs while ``DATABASE_URL`` stays unset.
"""
from __future__ import annotations

import os
import re
import uuid
from collections.abc import Iterator
from contextlib import contextmanager
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from shopifyseo.db import Backend, get_connection
from shopifyseo.db.compat import _translate_placeholders

_PG_PREFIXES = ("postgresql://", "postgres://")


def postgres_test_url() -> str | None:
    """Return ``TEST_DATABASE_URL`` when it is a Postgres URL, else ``None``."""
    url = os.environ.get("TEST_DATABASE_URL", "").strip()
    if url.lower().startswith(_PG_PREFIXES):
        return url
    return None


def resolve_backend() -> Backend:
    """Backend selected by ``TEST_DATABASE_URL`` (SQLite unless Postgres URL)."""
    return Backend.POSTGRES if postgres_test_url() else Backend.SQLITE


def _pg_ident(name: str) -> str:
    """Quote a known-safe SQL identifier (hex schema names from this module)."""
    if not name.isidentifier() or not name.isascii():
        raise ValueError(f"refusing to use {name!r} as a Postgres identifier")
    return name


_INT_PK_AUTOINCREMENT = re.compile(
    r"\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b",
    re.IGNORECASE,
)
_INT_PK = re.compile(r"\bINTEGER\s+PRIMARY\s+KEY\b", re.IGNORECASE)
_INSERT_OR_IGNORE = re.compile(r"\bINSERT\s+OR\s+IGNORE\s+INTO\b", re.IGNORECASE)
_ON_CONFLICT = re.compile(r"\bON\s+CONFLICT\b", re.IGNORECASE)
_IDENTITY_DDL = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"


class _NoopCursor:
    """Result of a skipped SQLite PRAGMA on a Postgres test connection."""

    def fetchone(self) -> None:
        return None

    def fetchall(self) -> list:
        return []

    def fetchmany(self, *args: Any, **kwargs: Any) -> list:
        return []


def _is_pragma(sql: str) -> bool:
    return sql.lstrip().upper().startswith("PRAGMA")


def _split_sql_statements(script: str) -> list[str]:
    """Split a SQLite ``executescript`` body on semicolons outside quotes."""
    statements: list[str] = []
    buf: list[str] = []
    quote: str | None = None
    i = 0
    while i < len(script):
        ch = script[i]
        if quote:
            buf.append(ch)
            if ch == quote:
                if i + 1 < len(script) and script[i + 1] == quote:
                    buf.append(script[i + 1])
                    i += 2
                    continue
                quote = None
            i += 1
            continue
        if ch in ("'", '"'):
            quote = ch
            buf.append(ch)
            i += 1
            continue
        if ch == "-" and i + 1 < len(script) and script[i + 1] == "-":
            while i < len(script) and script[i] != "\n":
                i += 1
            continue
        if ch == ";":
            stmt = "".join(buf).strip()
            if stmt:
                statements.append(stmt)
            buf = []
            i += 1
            continue
        buf.append(ch)
        i += 1
    stmt = "".join(buf).strip()
    if stmt:
        statements.append(stmt)
    return statements


def rewrite_sqlite_ddl_for_postgres(sql: str) -> str:
    """Rewrite SQLite-only DDL fragments that production schema helpers still emit."""
    sql = _INT_PK_AUTOINCREMENT.sub(_IDENTITY_DDL, sql)
    sql = _INT_PK.sub(_IDENTITY_DDL, sql)
    if _INSERT_OR_IGNORE.search(sql) and not _ON_CONFLICT.search(sql):
        sql = _INSERT_OR_IGNORE.sub("INSERT INTO", sql)
        sql = sql.rstrip().rstrip(";") + " ON CONFLICT DO NOTHING"
    return sql


def adapt_postgres_test_connection(conn: Any) -> Any:
    """Make a testdb Postgres connection accept SQLite-shaped SQL from tests.

    ``DATABASE_URL`` stays unset (plan 7a), so production ``conn.execute`` still
    uses ``?``. This wrap translates placeholders, implements ``executescript``,
    skips PRAGMA, and rewrites AUTOINCREMENT / INSERT OR IGNORE. Idempotent.
    The object stays a ``psycopg.Connection`` (isinstance checks in 7a fixture
    tests keep working).
    """
    if getattr(conn, "_shopifyseo_testdb_adapted", False):
        return conn

    orig_execute = conn.execute
    # psycopg3 Connection has execute only; executemany lives on Cursor.
    orig_executemany = getattr(conn, "executemany", None)

    def execute(query: Any, params: Any = None, **kwargs: Any) -> Any:
        if isinstance(query, str):
            if _is_pragma(query):
                return _NoopCursor()
            query = rewrite_sqlite_ddl_for_postgres(query)
            if "?" in query:
                query = _translate_placeholders(
                    query, to_postgres=True, escape_percent=params is not None
                )
        if params is None and not kwargs:
            return orig_execute(query)
        return orig_execute(query, params, **kwargs)

    def executemany(query: Any, params_seq: Any, **kwargs: Any) -> Any:
        if isinstance(query, str):
            query = rewrite_sqlite_ddl_for_postgres(query)
            if "?" in query:
                query = _translate_placeholders(
                    query, to_postgres=True, escape_percent=True
                )
        if orig_executemany is not None:
            return orig_executemany(query, params_seq, **kwargs)
        cur = conn.cursor()
        cur.executemany(query, params_seq, **kwargs)
        return cur

    def executescript(script: str) -> None:
        for statement in _split_sql_statements(script):
            execute(statement)
            try:
                conn.commit()
            except Exception:
                pass

    conn.execute = execute
    conn.executemany = executemany
    conn.executescript = executescript
    conn._shopifyseo_testdb_adapted = True
    return conn


@dataclass
class TestDatabase:
    """Isolated database for one test (or one module, if the fixture is module-scoped)."""

    backend: Backend
    url: str | None = None
    path: Path | None = None
    schema: str | None = None

    @property
    def is_postgres(self) -> bool:
        return self.backend == Backend.POSTGRES

    def connect(self, **kwargs: Any) -> Any:
        """Open a connection through ``shopifyseo.db.get_connection``.

        On Postgres, sets ``search_path`` to this test's schema so DDL does not
        leak into ``public``. Session ``timezone=UTC`` comes from the production
        connect path (libpq options), not from this SET.
        """
        if self.backend == Backend.POSTGRES:
            if not self.url:
                raise RuntimeError("postgres TestDatabase is missing url")
            conn = get_connection(url=self.url, **kwargs)
            if self.schema:
                ident = _pg_ident(self.schema)
                conn.execute(f"SET search_path TO {ident}, public")
                conn.commit()
            return adapt_postgres_test_connection(conn)
        path = kwargs.pop("path", None) or self.path
        kwargs.setdefault("check_same_thread", False)
        return get_connection(path=path, **kwargs)


def _create_postgres_schema(url: str) -> str:
    schema = f"t{uuid.uuid4().hex}"
    admin = get_connection(url=url)
    try:
        admin.execute(f"CREATE SCHEMA {_pg_ident(schema)}")
        admin.commit()
    finally:
        admin.close()
    return schema


def _drop_postgres_schema(url: str, schema: str) -> None:
    admin = get_connection(url=url)
    try:
        admin.execute(f"DROP SCHEMA IF EXISTS {_pg_ident(schema)} CASCADE")
        admin.commit()
    finally:
        admin.close()


@contextmanager
def make_testdb(tmp_path: Path) -> Iterator[TestDatabase]:
    """Yield an isolated ``TestDatabase`` and tear it down.

    SQLite: one temp file under ``tmp_path``. Postgres: a unique schema in the
    database named by ``TEST_DATABASE_URL`` (CI service or local port 5433).
    """
    url = postgres_test_url()
    if url:
        schema = _create_postgres_schema(url)
        db = TestDatabase(backend=Backend.POSTGRES, url=url, schema=schema)
        try:
            yield db
        finally:
            _drop_postgres_schema(url, schema)
        return

    path = tmp_path / "test.sqlite3"
    yield TestDatabase(backend=Backend.SQLITE, path=path)
