"""Dual-backend test database helpers (PostgreSQL plan 7a).

``TEST_DATABASE_URL`` selects the backend for the shared fixtures in
``tests/conftest.py``:

- Unset / empty / non-postgres: SQLite temp file (today's smoke default).
- ``postgresql://`` or ``postgres://``: open via ``shopifyseo.db.get_connection``
  (same path as production ``connect()``), so session ``timezone=UTC`` and
  CURRENT_TIMESTAMP → naive UTC text from plan 6 still apply.

Plan 7b–d should migrate ``sqlite3.connect`` call sites onto ``testdb`` /
``db_conn`` rather than adding a second fixture stack.

Postgres ``testdb`` connections are adapted so leftover SQLite-shaped SQL in
tests and production DDL (`?` placeholders, ``executescript``, AUTOINCREMENT,
``INSERT OR IGNORE`` / ``INSERT OR REPLACE``, ``REAL``, ``datetime('now')``,
PRAGMA) still runs while ``DATABASE_URL`` stays unset.
"""
from __future__ import annotations

import os
import re
import uuid
from collections.abc import Iterator
from contextlib import contextmanager
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from shopifyseo.db import Backend, PG_NOW_TEXT_SQL, apply_postgres_runtime_compat, get_connection

_PG_PREFIXES = ("postgresql://", "postgres://")


def postgres_test_url() -> str | None:
    """Return ``TEST_DATABASE_URL`` when it is a Postgres URL, else ``None``."""
    url = os.environ.get("TEST_DATABASE_URL", "").strip()
    if url.lower().startswith(_PG_PREFIXES):
        return url
    return None


def resolve_backend() -> Backend:
    """Backend selected by ``TEST_DATABASE_URL`` (SQLite unless Postgres URL)."""
    return Backend.POSTGRES if postgres_test_url() else Backend.SQLITE


def _pg_ident(name: str) -> str:
    """Quote a known-safe SQL identifier (hex schema names from this module)."""
    if not name.isidentifier() or not name.isascii():
        raise ValueError(f"refusing to use {name!r} as a Postgres identifier")
    return name


_INT_PK_AUTOINCREMENT = re.compile(
    r"\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b",
    re.IGNORECASE,
)
_INT_PK = re.compile(r"\bINTEGER\s+PRIMARY\s+KEY\b", re.IGNORECASE)
_INTEGER_TYPE = re.compile(r"\bINTEGER\b", re.IGNORECASE)
_BLOB_TYPE = re.compile(r"\bBLOB\b")
_REAL_TYPE = re.compile(r"\bREAL\b", re.IGNORECASE)
_INSERT_OR_IGNORE = re.compile(r"\bINSERT\s+OR\s+IGNORE\s+INTO\b", re.IGNORECASE)
_INSERT_OR_REPLACE = re.compile(
    r"\bINSERT\s+OR\s+REPLACE\s+INTO\s+([A-Za-z_][\w]*)\s*\(([^)]+)\)",
    re.IGNORECASE,
)
_ON_CONFLICT = re.compile(r"\bON\s+CONFLICT\b", re.IGNORECASE)
_DATETIME_NOW = re.compile(r"\bdatetime\(\s*'now'\s*\)", re.IGNORECASE)
# Plan 6 ``PG_NOW_TEXT_SQL`` — must not embed CURRENT_TIMESTAMP. Production
# execute already rewrites that token to a TEXT expression; wrapping the
# result in ``AT TIME ZONE`` yields ``timezone(unknown, text)``.
_LAST_INSERT_ROWID = re.compile(r"\blast_insert_rowid\s*\(\s*\)", re.IGNORECASE)
_SQLITE_RAISE_TRIGGER = re.compile(
    r"^\s*CREATE\s+TRIGGER\b.*\bRAISE\s*\(\s*ABORT\s*,",
    re.IGNORECASE | re.DOTALL,
)
_PRAGMA_TABLE_INFO = re.compile(
    r"""^\s*PRAGMA\s+table_info\(\s*(?:["']([^"']+)["']|([A-Za-z_][\w]*))\s*\)\s*;?\s*$""",
    re.IGNORECASE,
)
_IDENTITY_DDL = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
_DML_HEAD = re.compile(r"^\s*(INSERT|UPDATE|DELETE)\b", re.IGNORECASE)


def _coerce_sql_params(params: Any) -> Any:
    """SQLite treats bool as int; Postgres BIGINT rejects bound ``True``/``False``."""
    if params is None:
        return None
    if isinstance(params, (tuple, list)):
        return type(params)(int(p) if isinstance(p, bool) else p for p in params)
    return params


class _NoopCursor:
    """Result of a skipped SQLite PRAGMA on a Postgres test connection."""

    def fetchone(self) -> None:
        return None

    def fetchall(self) -> list:
        return []

    def fetchmany(self, *args: Any, **kwargs: Any) -> list:
        return []

    def __iter__(self):
        return iter(())


class _PragmaTableInfoCursor:
    """sqlite3 ``PRAGMA table_info`` shape: ``(cid, name, type, notnull, dflt, pk)``."""

    def __init__(self, rows: list[tuple[Any, ...]]) -> None:
        self._rows = rows
        self._i = 0

    def fetchone(self) -> tuple[Any, ...] | None:
        if self._i >= len(self._rows):
            return None
        row = self._rows[self._i]
        self._i += 1
        return row

    def fetchall(self) -> list[tuple[Any, ...]]:
        rest = self._rows[self._i :]
        self._i = len(self._rows)
        return rest

    def fetchmany(self, size: int | None = None, *args: Any, **kwargs: Any) -> list[tuple[Any, ...]]:
        if size is None:
            return self.fetchall()
        chunk = self._rows[self._i : self._i + size]
        self._i += len(chunk)
        return chunk

    def __iter__(self):
        return iter(self.fetchall())


def _is_pragma(sql: str) -> bool:
    return sql.lstrip().upper().startswith("PRAGMA")


def _pragma_table_name(sql: str) -> str | None:
    match = _PRAGMA_TABLE_INFO.match(sql)
    if not match:
        return None
    return match.group(1) or match.group(2)


def _split_sql_statements(script: str) -> list[str]:
    """Split a SQLite ``executescript`` body on semicolons outside quotes."""
    statements: list[str] = []
    buf: list[str] = []
    quote: str | None = None
    i = 0
    while i < len(script):
        ch = script[i]
        if quote:
            buf.append(ch)
            if ch == quote:
                if i + 1 < len(script) and script[i + 1] == quote:
                    buf.append(script[i + 1])
                    i += 2
                    continue
                quote = None
            i += 1
            continue
        if ch in ("'", '"'):
            quote = ch
            buf.append(ch)
            i += 1
            continue
        if ch == "-" and i + 1 < len(script) and script[i + 1] == "-":
            while i < len(script) and script[i] != "\n":
                i += 1
            continue
        if ch == ";":
            stmt = "".join(buf).strip()
            if stmt:
                statements.append(stmt)
            buf = []
            i += 1
            continue
        buf.append(ch)
        i += 1
    stmt = "".join(buf).strip()
    if stmt:
        statements.append(stmt)
    return statements


def rewrite_sqlite_ddl_for_postgres(sql: str) -> str:
    """Rewrite SQLite-only DDL fragments that production schema helpers still emit.

    Type rewrites apply only to ``CREATE`` / ``ALTER`` so identifiers such as a
    column named ``blob`` in ``SELECT`` / ``INSERT`` are left alone. SQLite
    ``INTEGER`` is 64-bit; Postgres ``INTEGER`` is 32-bit, so leftover epoch /
    sentinel values overflow unless remaining integer columns become ``BIGINT``.
    ``BLOB`` becomes ``BYTEA``. ``REAL`` becomes ``DOUBLE PRECISION``.
    ``INSERT OR REPLACE INTO t (pk, …)`` becomes ``ON CONFLICT (pk) DO UPDATE``.
    ``datetime('now')`` becomes plan-6 ``PG_NOW_TEXT_SQL`` (naive UTC text via
    ``now()``, not ``CURRENT_TIMESTAMP``, so the production token rewrite
    cannot wrap text in ``AT TIME ZONE``).     ``last_insert_rowid()`` becomes
    ``lastval()`` so leftover tests that read the IDENTITY after INSERT hit
    Postgres without changing production helpers.
    """
    head = sql.lstrip()[:12].upper()
    if head.startswith("CREATE") or head.startswith("ALTER"):
        sql = _INT_PK_AUTOINCREMENT.sub(_IDENTITY_DDL, sql)
        sql = _INT_PK.sub(_IDENTITY_DDL, sql)
        sql = _INTEGER_TYPE.sub("BIGINT", sql)
        sql = _BLOB_TYPE.sub("BYTEA", sql)
        sql = _REAL_TYPE.sub("DOUBLE PRECISION", sql)
    if _INSERT_OR_IGNORE.search(sql) and not _ON_CONFLICT.search(sql):
        sql = _INSERT_OR_IGNORE.sub("INSERT INTO", sql)
        sql = sql.rstrip().rstrip(";") + " ON CONFLICT DO NOTHING"
    replace = _INSERT_OR_REPLACE.search(sql)
    if replace and not _ON_CONFLICT.search(sql):
        cols = [c.strip() for c in replace.group(2).split(",") if c.strip()]
        if cols:
            assignments = ", ".join(f"{c} = excluded.{c}" for c in cols[1:] or cols)
            sql = _INSERT_OR_REPLACE.sub(rf"INSERT INTO {replace.group(1)} ({replace.group(2)})", sql, count=1)
            sql = sql.rstrip().rstrip(";") + f" ON CONFLICT ({cols[0]}) DO UPDATE SET {assignments}"
    sql = _DATETIME_NOW.sub(PG_NOW_TEXT_SQL, sql)
    sql = _LAST_INSERT_ROWID.sub("lastval()", sql)
    return sql


def adapt_postgres_test_connection(conn: Any) -> Any:
    """Make a testdb Postgres connection accept SQLite-shaped SQL from tests.

    Shared production compat (``?`` translation, bool dump, NUMERIC load,
    ``executemany``) comes from ``apply_postgres_runtime_compat``. This wrap
    adds testdb-only behaviour: ``executescript``, ``PRAGMA table_info``,
    other PRAGMA no-ops, rollback-on-error, and SQLite DDL rewrites
    (AUTOINCREMENT / INTEGER / BLOB / REAL / INSERT OR IGNORE / INSERT OR
    REPLACE / ``datetime('now')`` / ``last_insert_rowid()``). Bound Python
    ``bool`` values become ``0``/``1``. Exposes ``total_changes`` like sqlite3.
    Idempotent. The object stays a ``psycopg.Connection``.
    """
    # Shared production compat first so testdb cannot drift from connect_postgres.
    apply_postgres_runtime_compat(conn)
    if getattr(conn, "_shopifyseo_testdb_adapted", False):
        return conn

    orig_execute = conn.execute
    # Production compat (or a leftover raw connection) may already expose executemany.
    orig_executemany = getattr(conn, "executemany", None)
    conn.total_changes = 0

    def _bump_total_changes(query: Any, result: Any) -> None:
        if not isinstance(query, str) or not _DML_HEAD.match(query):
            return
        n = getattr(result, "rowcount", 0) or 0
        if n > 0:
            conn.total_changes += int(n)

    def _rollback_failed_transaction() -> None:
        """SQLite lets the next statement run after an error; Postgres does not."""
        try:
            conn.rollback()
        except Exception:
            pass

    def _pragma_table_info(table: str) -> _PragmaTableInfoCursor:
        rows = orig_execute(
            """
            SELECT a.attname,
                   format_type(a.atttypid, a.atttypmod),
                   CASE WHEN a.attnotnull THEN 1 ELSE 0 END,
                   pg_get_expr(ad.adbin, ad.adrelid),
                   CASE WHEN EXISTS (
                       SELECT 1 FROM pg_constraint c
                       WHERE c.conrelid = a.attrelid
                         AND c.contype = 'p'
                         AND a.attnum = ANY (c.conkey)
                   ) THEN 1 ELSE 0 END
            FROM pg_attribute a
            LEFT JOIN pg_attrdef ad
              ON ad.adrelid = a.attrelid AND ad.adnum = a.attnum
            JOIN pg_class cls ON cls.oid = a.attrelid
            JOIN pg_namespace n ON n.oid = cls.relnamespace
            WHERE cls.relname = ?
              AND a.attnum > 0 AND NOT a.attisdropped
              AND (
                  n.nspname = current_schema()
                  OR starts_with(n.nspname, 'pg_temp')
              )
            ORDER BY a.attnum
            """,
            (table,),
        ).fetchall()
        shaped = [(i, r[0], r[1], r[2], r[3], r[4]) for i, r in enumerate(rows)]
        return _PragmaTableInfoCursor(shaped)

    def execute(query: Any, params: Any = None, **kwargs: Any) -> Any:
        try:
            if isinstance(query, str):
                if _is_pragma(query):
                    table = _pragma_table_name(query)
                    if table:
                        return _pragma_table_info(table)
                    return _NoopCursor()
                if _SQLITE_RAISE_TRIGGER.search(query):
                    # SQLite RAISE(ABORT) trigger bodies are not valid Postgres.
                    # Testdb-only skip; live SQLite still installs them.
                    return _NoopCursor()
                query = rewrite_sqlite_ddl_for_postgres(query)
                # ``?`` → ``%s`` and bool dump live in production apply_postgres_runtime_compat.
            params = _coerce_sql_params(params)
            if params is None and not kwargs:
                result = orig_execute(query)
            else:
                result = orig_execute(query, params, **kwargs)
            _bump_total_changes(query, result)
            return result
        except Exception:
            _rollback_failed_transaction()
            raise

    def executemany(query: Any, params_seq: Any, **kwargs: Any) -> Any:
        try:
            if isinstance(query, str):
                query = rewrite_sqlite_ddl_for_postgres(query)
            if isinstance(params_seq, (list, tuple)):
                params_seq = [_coerce_sql_params(row) for row in params_seq]
            if orig_executemany is not None:
                result = orig_executemany(query, params_seq, **kwargs)
            else:
                cur = conn.cursor()
                cur.executemany(query, params_seq, **kwargs)
                result = cur
            _bump_total_changes(query, result)
            return result
        except Exception:
            _rollback_failed_transaction()
            raise

    def executescript(script: str) -> None:
        for statement in _split_sql_statements(script):
            execute(statement)
            try:
                conn.commit()
            except Exception:
                pass

    conn.execute = execute
    conn.executemany = executemany
    conn.executescript = executescript
    conn._shopifyseo_testdb_adapted = True
    return conn


@dataclass
class TestDatabase:
    """Isolated database for one test (or one module, if the fixture is module-scoped)."""

    backend: Backend
    url: str | None = None
    path: Path | None = None
    schema: str | None = None

    @property
    def is_postgres(self) -> bool:
        return self.backend == Backend.POSTGRES

    def connect(self, **kwargs: Any) -> Any:
        """Open a connection through ``shopifyseo.db.get_connection``.

        On Postgres, sets ``search_path`` to this test's schema so DDL does not
        leak into ``public``. Session ``timezone=UTC`` comes from the production
        connect path (libpq options), not from this SET.
        """
        if self.backend == Backend.POSTGRES:
            if not self.url:
                raise RuntimeError("postgres TestDatabase is missing url")
            # autocommit matches SQLite DDL auto-commit so a failed statement
            # (often swallowed by production ``except: pass``) does not abort
            # the rest of ensure_dashboard_schema.
            kwargs.setdefault("autocommit", True)
            conn = get_connection(url=self.url, **kwargs)
            if self.schema:
                ident = _pg_ident(self.schema)
                conn.execute(f"SET search_path TO {ident}, public")
            return adapt_postgres_test_connection(conn)
        path = kwargs.pop("path", None) or self.path
        kwargs.setdefault("check_same_thread", False)
        return get_connection(path=path, **kwargs)


def _create_postgres_schema(url: str) -> str:
    schema = f"t{uuid.uuid4().hex}"
    admin = get_connection(url=url)
    try:
        admin.execute(f"CREATE SCHEMA {_pg_ident(schema)}")
        admin.commit()
    finally:
        admin.close()
    return schema


def _drop_postgres_schema(url: str, schema: str) -> None:
    admin = get_connection(url=url)
    try:
        admin.execute(f"DROP SCHEMA IF EXISTS {_pg_ident(schema)} CASCADE")
        admin.commit()
    finally:
        admin.close()


@contextmanager
def make_testdb(tmp_path: Path) -> Iterator[TestDatabase]:
    """Yield an isolated ``TestDatabase`` and tear it down.

    SQLite: one temp file under ``tmp_path``. Postgres: a unique schema in the
    database named by ``TEST_DATABASE_URL`` (CI service or local port 5433).
    """
    url = postgres_test_url()
    if url:
        schema = _create_postgres_schema(url)
        db = TestDatabase(backend=Backend.POSTGRES, url=url, schema=schema)
        try:
            yield db
        finally:
            _drop_postgres_schema(url, schema)
        return

    path = tmp_path / "test.sqlite3"
    yield TestDatabase(backend=Backend.SQLITE, path=path)
