"""Lint-style test to track direct conn.execute() call sites.

This test ensures that new code uses the shopifyseo.db.execute wrapper instead
of calling conn.execute() directly. Direct calls are tracked in an allowlist
that can only shrink over time as code is migrated.

The allowlist helps ensure:
1. New code uses the wrapper for proper % escaping on PostgreSQL
2. Migration progress is visible and tracked
3. CI fails if new direct execute sites are added

Migration plan:
- PR2 (this PR): Infrastructure + team_tasks.py + api_usage.py
- PR3-5: Remaining modules (740 sites total at baseline)
"""
import re
from pathlib import Path

import pytest


ALLOWED_DIRECT_EXECUTE_SITES: set[str] = {
    # =========================================================================
    # backend/app/db.py - Connection setup (uses PRAGMAs, SQLite-specific)
    # =========================================================================
    "backend/app/db.py:32",
    "backend/app/db.py:50",
    "backend/app/db.py:63",
    "backend/app/db.py:64",
    # =========================================================================
    # backend/app/routers/ - API routers (PR3+)
    # =========================================================================
    "backend/app/routers/article_ideas.py:279",
    "backend/app/routers/blogs.py:1313",
    "backend/app/routers/blogs.py:147",
    "backend/app/routers/blogs.py:162",
    "backend/app/routers/blogs.py:176",
    "backend/app/routers/blogs.py:238",
    "backend/app/routers/blogs.py:322",
    "backend/app/routers/blogs.py:495",
    "backend/app/routers/blogs.py:572",
    "backend/app/routers/blogs.py:596",
    "backend/app/routers/blogs.py:629",
    "backend/app/routers/blogs.py:654",
    "backend/app/routers/internal_links.py:100",
    "backend/app/routers/internal_links.py:174",
    "backend/app/routers/internal_links.py:200",
    "backend/app/routers/internal_links.py:204",
    "backend/app/routers/internal_links.py:340",
    "backend/app/routers/internal_links.py:345",
    "backend/app/routers/internal_links.py:349",
    "backend/app/routers/internal_links.py:35",
    "backend/app/routers/internal_links.py:38",
    "backend/app/routers/internal_links.py:414",
    "backend/app/routers/internal_links.py:416",
    "backend/app/routers/internal_links.py:431",
    "backend/app/routers/internal_links.py:436",
    "backend/app/routers/internal_links.py:490",
    "backend/app/routers/internal_links.py:557",
    "backend/app/routers/internal_links.py:581",
    "backend/app/routers/internal_links.py:607",
    "backend/app/routers/internal_links.py:642",
    "backend/app/routers/internal_links.py:680",
    "backend/app/routers/internal_links.py:697",
    "backend/app/routers/internal_links.py:718",
    "backend/app/routers/internal_links.py:733",
    "backend/app/routers/internal_links.py:745",
    "backend/app/routers/internal_links.py:751",
    "backend/app/routers/internal_links.py:80",
    "backend/app/routers/internal_links.py:84",
    "backend/app/routers/internal_links.py:96",
    "backend/app/routers/keywords.py:123",
    "backend/app/routers/keywords.py:134",
    "backend/app/routers/keywords.py:145",
    "backend/app/routers/keywords.py:284",
    "backend/app/routers/keywords.py:375",
    "backend/app/routers/keywords.py:475",
    "backend/app/routers/keywords.py:497",
    "backend/app/routers/keywords.py:516",
    "backend/app/routers/keywords.py:620",
    "backend/app/routers/keywords.py:623",
    "backend/app/routers/keywords.py:628",
    "backend/app/routers/keywords.py:640",
    "backend/app/routers/keywords.py:641",
    "backend/app/routers/keywords.py:642",
    # =========================================================================
    # backend/app/services/ - Service layer (PR3+)
    # =========================================================================
    "backend/app/services/article_service.py:100",
    "backend/app/services/image_seo_service/_catalog.py:124",
    "backend/app/services/image_seo_service/_catalog.py:392",
    "backend/app/services/image_seo_service/_catalog.py:418",
    "backend/app/services/image_seo_service/_catalog.py:477",
    "backend/app/services/image_seo_service/_catalog.py:512",
    "backend/app/services/image_seo_service/_catalog.py:587",
    "backend/app/services/image_seo_service/_catalog.py:59",
    "backend/app/services/image_seo_service/_catalog.py:657",
    "backend/app/services/image_seo_service/_catalog.py:74",
    "backend/app/services/image_seo_service/_optimizer.py:200",
    "backend/app/services/image_seo_service/_optimizer.py:475",
    "backend/app/services/image_seo_service/_optimizer.py:921",
    "backend/app/services/index_evidence.py:13",
    "backend/app/services/index_evidence.py:22",
    "backend/app/services/keyword_clustering/_context.py:140",
    "backend/app/services/keyword_clustering/_crud.py:110",
    "backend/app/services/keyword_clustering/_crud.py:169",
    "backend/app/services/keyword_clustering/_crud.py:177",
    "backend/app/services/keyword_clustering/_crud.py:187",
    "backend/app/services/keyword_clustering/_crud.py:197",
    "backend/app/services/keyword_clustering/_crud.py:20",
    "backend/app/services/keyword_clustering/_crud.py:207",
    "backend/app/services/keyword_clustering/_crud.py:24",
    "backend/app/services/keyword_clustering/_crud.py:28",
    "backend/app/services/keyword_clustering/_crud.py:49",
    "backend/app/services/keyword_clustering/_crud.py:54",
    "backend/app/services/keyword_clustering/_crud.py:59",
    "backend/app/services/keyword_clustering/_crud.py:84",
    "backend/app/services/keyword_clustering/_crud.py:89",
    "backend/app/services/keyword_clustering/_gaps.py:112",
    "backend/app/services/keyword_clustering/_gaps.py:144",
    "backend/app/services/keyword_clustering/_gaps.py:149",
    "backend/app/services/keyword_clustering/_gaps.py:156",
    "backend/app/services/keyword_clustering/_gaps.py:168",
    "backend/app/services/keyword_clustering/_gaps.py:182",
    "backend/app/services/keyword_clustering/_generation.py:203",
    "backend/app/services/keyword_clustering/_generation.py:204",
    "backend/app/services/keyword_clustering/_generation.py:205",
    "backend/app/services/keyword_clustering/_generation.py:487",
    "backend/app/services/keyword_clustering/_generation.py:488",
    "backend/app/services/keyword_clustering/_generation.py:546",
    "backend/app/services/keyword_clustering/_generation.py:551",
    "backend/app/services/keyword_clustering/_generation.py:575",
    "backend/app/services/keyword_clustering/_generation.py:578",
    "backend/app/services/keyword_clustering/_planning.py:212",
    "backend/app/services/keyword_clustering/_planning.py:218",
    "backend/app/services/keyword_clustering/_planning.py:561",
    "backend/app/services/keyword_clustering/_storage.py:115",
    "backend/app/services/keyword_clustering/_storage.py:117",
    "backend/app/services/keyword_clustering/_storage.py:122",
    "backend/app/services/keyword_clustering/_storage.py:169",
    "backend/app/services/keyword_clustering/_storage.py:175",
    "backend/app/services/keyword_clustering/_storage.py:180",
    "backend/app/services/keyword_clustering/_storage.py:20",
    "backend/app/services/keyword_clustering/_storage.py:26",
    "backend/app/services/keyword_clustering/_storage.py:28",
    "backend/app/services/keyword_clustering/_storage.py:35",
    "backend/app/services/keyword_clustering/_storage.py:41",
    "backend/app/services/keyword_clustering/_storage.py:65",
    "backend/app/services/keyword_clustering/_storage.py:91",
    "backend/app/services/keyword_clustering/_store_fit.py:319",
    "backend/app/services/keyword_research/competitor_blocklist.py:137",
    "backend/app/services/keyword_research/competitor_blocklist.py:138",
    "backend/app/services/keyword_research/competitor_blocklist.py:139",
    "backend/app/services/keyword_research/keyword_db.py:244",
    "backend/app/services/keyword_research/keyword_db.py:257",
    "backend/app/services/keyword_research/keyword_db.py:279",
    "backend/app/services/keyword_research/keyword_db.py:313",
    "backend/app/services/keyword_research/keyword_db.py:341",
    "backend/app/services/keyword_research/keyword_db.py:369",
    "backend/app/services/keyword_research/keyword_db.py:466",
    "backend/app/services/keyword_research/keyword_db.py:478",
    "backend/app/services/keyword_research/keyword_db.py:500",
    "backend/app/services/keyword_research/keyword_db.py:513",
    "backend/app/services/keyword_research/keyword_db.py:547",
    "backend/app/services/keyword_research/keyword_db.py:613",
    "backend/app/services/keyword_research/keyword_db.py:624",
    "backend/app/services/keyword_research/keyword_db.py:646",
    "backend/app/services/keyword_research/keyword_db.py:656",
    "backend/app/services/keyword_research/keyword_db.py:685",
    "backend/app/services/keyword_research/keyword_db.py:693",
    "backend/app/services/keyword_research/keyword_db.py:715",
    "backend/app/services/keyword_research/keyword_db.py:760",
    "backend/app/services/keyword_research/keyword_db.py:852",
    "backend/app/services/keyword_research/research_runner.py:509",
    "backend/app/services/open_page_rank.py:224",
    "backend/app/services/open_page_rank.py:248",
    "backend/app/services/open_page_rank.py:267",
    "backend/app/services/open_page_rank.py:276",
    "backend/app/services/open_page_rank.py:298",
    "backend/app/services/open_page_rank.py:304",
    "backend/app/services/open_page_rank.py:329",
    "backend/app/services/open_page_rank.py:338",
    "backend/app/services/opportunities_service.py:192",
    "backend/app/services/opportunities_service.py:202",
    "backend/app/services/opportunities_service.py:288",
    "backend/app/services/opportunities_service.py:291",
    "backend/app/services/opportunities_service.py:296",
    "backend/app/services/opportunities_service.py:301",
    "backend/app/services/overview_results.py:10",
    "backend/app/services/overview_results.py:25",
    "backend/app/services/rank_tracking.py:112",
    "backend/app/services/rank_tracking.py:125",
    "backend/app/services/rank_tracking.py:129",
    "backend/app/services/rank_tracking.py:132",
    "backend/app/services/rank_tracking.py:140",
    "backend/app/services/rank_tracking.py:145",
    "backend/app/services/rank_tracking.py:156",
    "backend/app/services/rank_tracking.py:164",
    "backend/app/services/rank_tracking.py:166",
    "backend/app/services/rank_tracking.py:170",
    "backend/app/services/rank_tracking.py:181",
    "backend/app/services/rank_tracking.py:182",
    "backend/app/services/rank_tracking.py:191",
    "backend/app/services/rank_tracking.py:192",
    "backend/app/services/rank_tracking.py:194",
    "backend/app/services/rank_tracking.py:207",
    "backend/app/services/rank_tracking.py:210",
    "backend/app/services/rank_tracking.py:214",
    "backend/app/services/rank_tracking.py:226",
    "backend/app/services/rank_tracking.py:227",
    "backend/app/services/rank_tracking.py:23",
    "backend/app/services/rank_tracking.py:230",
    "backend/app/services/rank_tracking.py:232",
    "backend/app/services/rank_tracking.py:233",
    "backend/app/services/rank_tracking.py:243",
    "backend/app/services/rank_tracking.py:247",
    "backend/app/services/rank_tracking.py:253",
    "backend/app/services/rank_tracking.py:256",
    "backend/app/services/rank_tracking.py:270",
    "backend/app/services/rank_tracking.py:271",
    "backend/app/services/rank_tracking.py:275",
    "backend/app/services/rank_tracking.py:29",
    "backend/app/services/rank_tracking.py:30",
    "backend/app/services/rank_tracking.py:31",
    "backend/app/services/rank_tracking.py:45",
    "backend/app/services/rank_tracking.py:58",
    "backend/app/services/rank_tracking.py:62",
    "backend/app/services/rank_tracking.py:66",
    "backend/app/services/rank_tracking.py:74",
    "backend/app/services/rank_tracking.py:79",
    "backend/app/services/rank_tracking.py:81",
    "backend/app/services/rank_tracking.py:99",
    # team_tasks.py - Migrated in PR2, remaining are non-wrapper calls
    "backend/app/services/team_tasks.py:11",
    "backend/app/services/team_tasks.py:131",
    "backend/app/services/team_tasks.py:141",
    "backend/app/services/team_tasks.py:143",
    "backend/app/services/team_tasks.py:161",
    "backend/app/services/team_tasks.py:162",
    "backend/app/services/team_tasks.py:183",
    "backend/app/services/team_tasks.py:35",
    "backend/app/services/team_tasks.py:36",
    "backend/app/services/team_tasks.py:59",
    # =========================================================================
    # shopifyseo/ - Core library (PR4+)
    # =========================================================================
    "shopifyseo/api_usage.py:118",
    "shopifyseo/api_usage.py:239",
    "shopifyseo/api_usage.py:254",
    "shopifyseo/api_usage.py:269",
    "shopifyseo/api_usage.py:285",
    "shopifyseo/api_usage.py:300",
    "shopifyseo/api_usage.py:313",
    "shopifyseo/api_usage.py:324",
    "shopifyseo/api_usage.py:337",
    "shopifyseo/api_usage.py:350",
    "shopifyseo/api_usage.py:361",
    "shopifyseo/article_draft_retrieval.py:108",
    "shopifyseo/article_draft_retrieval.py:127",
    "shopifyseo/article_draft_retrieval.py:155",
    "shopifyseo/article_draft_retrieval.py:205",
    "shopifyseo/article_draft_retrieval.py:234",
    "shopifyseo/article_draft_retrieval.py:260",
    "shopifyseo/article_draft_retrieval.py:52",
    "shopifyseo/article_draft_retrieval.py:81",
    "shopifyseo/catalog_image_work.py:212",
    "shopifyseo/catalog_image_work.py:218",
    "shopifyseo/catalog_image_work.py:226",
    "shopifyseo/catalog_image_work.py:241",
    "shopifyseo/catalog_image_work.py:247",
    "shopifyseo/catalog_image_work.py:253",
    "shopifyseo/dashboard_actions/_state.py:387",
    "shopifyseo/dashboard_actions/_state.py:388",
    "shopifyseo/dashboard_actions/_state.py:389",
    "shopifyseo/dashboard_actions/_sync_pagespeed.py:54",
    "shopifyseo/dashboard_ai_engine_parts/_article_draft.py:1351",
    "shopifyseo/dashboard_ai_engine_parts/_article_draft.py:249",
    "shopifyseo/dashboard_ai_engine_parts/_article_draft.py:255",
    "shopifyseo/dashboard_ai_engine_parts/_article_draft.py:260",
    "shopifyseo/dashboard_ai_engine_parts/_article_draft.py:3138",
    "shopifyseo/dashboard_ai_engine_parts/_article_draft.py:3149",
    "shopifyseo/dashboard_ai_engine_parts/_article_draft.py:344",
    "shopifyseo/dashboard_ai_engine_parts/_article_draft.py:353",
    "shopifyseo/dashboard_ai_engine_parts/_article_draft.py:392",
    "shopifyseo/dashboard_ai_engine_parts/_article_draft.py:402",
    "shopifyseo/dashboard_ai_engine_parts/_article_draft.py:528",
    "shopifyseo/dashboard_ai_engine_parts/_article_draft.py:558",
    "shopifyseo/dashboard_ai_engine_parts/_article_draft.py:597",
    "shopifyseo/dashboard_ai_engine_parts/_article_draft.py:624",
    "shopifyseo/dashboard_ai_engine_parts/_article_ideas.py:123",
    "shopifyseo/dashboard_ai_engine_parts/_article_ideas.py:175",
    "shopifyseo/dashboard_ai_engine_parts/_article_ideas.py:192",
    "shopifyseo/dashboard_ai_engine_parts/_article_ideas.py:621",
    "shopifyseo/dashboard_ai_engine_parts/context.py:112",
    "shopifyseo/dashboard_ai_engine_parts/context.py:211",
    "shopifyseo/dashboard_ai_engine_parts/context.py:277",
    "shopifyseo/dashboard_ai_engine_parts/context.py:297",
    "shopifyseo/dashboard_ai_engine_parts/context.py:317",
    "shopifyseo/dashboard_ai_engine_parts/context.py:335",
    "shopifyseo/dashboard_ai_engine_parts/context.py:361",
    "shopifyseo/dashboard_ai_engine_parts/context.py:90",
    "shopifyseo/dashboard_ai_engine_parts/generation.py:183",
    "shopifyseo/dashboard_article_ideas.py:1014",
    "shopifyseo/dashboard_article_ideas.py:1016",
    "shopifyseo/dashboard_article_ideas.py:1184",
    "shopifyseo/dashboard_article_ideas.py:1217",
    "shopifyseo/dashboard_article_ideas.py:1234",
    "shopifyseo/dashboard_article_ideas.py:1250",
    "shopifyseo/dashboard_article_ideas.py:1283",
    "shopifyseo/dashboard_article_ideas.py:1340",
    "shopifyseo/dashboard_article_ideas.py:1373",
    "shopifyseo/dashboard_article_ideas.py:1380",
    "shopifyseo/dashboard_article_ideas.py:1401",
    "shopifyseo/dashboard_article_ideas.py:1410",
    "shopifyseo/dashboard_article_ideas.py:1422",
    "shopifyseo/dashboard_article_ideas.py:1464",
    "shopifyseo/dashboard_article_ideas.py:1478",
    "shopifyseo/dashboard_article_ideas.py:1489",
    "shopifyseo/dashboard_article_ideas.py:1498",
    "shopifyseo/dashboard_article_ideas.py:162",
    "shopifyseo/dashboard_article_ideas.py:1689",
    "shopifyseo/dashboard_article_ideas.py:1862",
    "shopifyseo/dashboard_article_ideas.py:189",
    "shopifyseo/dashboard_article_ideas.py:1895",
    "shopifyseo/dashboard_article_ideas.py:1949",
    "shopifyseo/dashboard_article_ideas.py:1984",
    "shopifyseo/dashboard_article_ideas.py:2023",
    "shopifyseo/dashboard_article_ideas.py:2091",
    "shopifyseo/dashboard_article_ideas.py:245",
    "shopifyseo/dashboard_article_ideas.py:252",
    "shopifyseo/dashboard_article_ideas.py:323",
    "shopifyseo/dashboard_article_ideas.py:331",
    "shopifyseo/dashboard_article_ideas.py:338",
    "shopifyseo/dashboard_article_ideas.py:346",
    "shopifyseo/dashboard_article_ideas.py:359",
    "shopifyseo/dashboard_article_ideas.py:363",
    "shopifyseo/dashboard_article_ideas.py:389",
    "shopifyseo/dashboard_article_ideas.py:392",
    "shopifyseo/dashboard_article_ideas.py:414",
    "shopifyseo/dashboard_article_ideas.py:448",
    "shopifyseo/dashboard_article_ideas.py:459",
    "shopifyseo/dashboard_article_ideas.py:484",
    "shopifyseo/dashboard_article_ideas.py:487",
    "shopifyseo/dashboard_article_ideas.py:529",
    "shopifyseo/dashboard_article_ideas.py:531",
    "shopifyseo/dashboard_article_ideas.py:558",
    "shopifyseo/dashboard_article_ideas.py:574",
    "shopifyseo/dashboard_article_ideas.py:599",
    "shopifyseo/dashboard_article_ideas.py:612",
    "shopifyseo/dashboard_article_ideas.py:630",
    "shopifyseo/dashboard_article_ideas.py:648",
    "shopifyseo/dashboard_article_ideas.py:714",
    "shopifyseo/dashboard_article_ideas.py:718",
    "shopifyseo/dashboard_article_ideas.py:722",
    "shopifyseo/dashboard_article_ideas.py:729",
    "shopifyseo/dashboard_article_ideas.py:804",
    "shopifyseo/dashboard_article_ideas.py:821",
    "shopifyseo/dashboard_article_ideas.py:878",
    "shopifyseo/dashboard_google/_auth.py:115",
    "shopifyseo/dashboard_google/_auth.py:124",
    "shopifyseo/dashboard_google/_auth.py:75",
    "shopifyseo/dashboard_google/_auth.py:87",
    "shopifyseo/dashboard_google/_cache.py:101",
    "shopifyseo/dashboard_google/_cache.py:167",
    "shopifyseo/dashboard_google/_cache.py:48",
    "shopifyseo/dashboard_google/_cache.py:64",
    "shopifyseo/dashboard_google/_cache.py:67",
    "shopifyseo/dashboard_google/_ga4.py:37",
    "shopifyseo/dashboard_google/_gsc.py:160",
    "shopifyseo/dashboard_google/_gsc.py:161",
    "shopifyseo/dashboard_google/_gsc.py:186",
    "shopifyseo/dashboard_google/_gsc.py:201",
    "shopifyseo/dashboard_queries/_basic_fetchers.py:144",
    "shopifyseo/dashboard_queries/_basic_fetchers.py:150",
    "shopifyseo/dashboard_queries/_basic_fetchers.py:156",
    "shopifyseo/dashboard_queries/_basic_fetchers.py:162",
    "shopifyseo/dashboard_queries/_basic_fetchers.py:169",
    "shopifyseo/dashboard_queries/_basic_fetchers.py:173",
    "shopifyseo/dashboard_queries/_basic_fetchers.py:177",
    "shopifyseo/dashboard_queries/_basic_fetchers.py:181",
    "shopifyseo/dashboard_queries/_basic_fetchers.py:185",
    "shopifyseo/dashboard_queries/_basic_fetchers.py:192",
    "shopifyseo/dashboard_queries/_basic_fetchers.py:203",
    "shopifyseo/dashboard_queries/_basic_fetchers.py:207",
    "shopifyseo/dashboard_queries/_basic_fetchers.py:223",
    "shopifyseo/dashboard_queries/_basic_fetchers.py:236",
    "shopifyseo/dashboard_queries/_basic_fetchers.py:254",
    "shopifyseo/dashboard_queries/_basic_fetchers.py:268",
    "shopifyseo/dashboard_queries/_basic_fetchers.py:271",
    "shopifyseo/dashboard_queries/_basic_fetchers.py:28",
    "shopifyseo/dashboard_queries/_basic_fetchers.py:283",
    "shopifyseo/dashboard_queries/_basic_fetchers.py:328",
    "shopifyseo/dashboard_queries/_basic_fetchers.py:380",
    "shopifyseo/dashboard_queries/_basic_fetchers.py:393",
    "shopifyseo/dashboard_queries/_basic_fetchers.py:75",
    "shopifyseo/dashboard_queries/_basic_fetchers.py:78",
    "shopifyseo/dashboard_queries/_basic_fetchers.py:83",
    "shopifyseo/dashboard_queries/_basic_fetchers.py:88",
    "shopifyseo/dashboard_queries/_editors.py:159",
    "shopifyseo/dashboard_queries/_editors.py:174",
    "shopifyseo/dashboard_queries/_editors.py:25",
    "shopifyseo/dashboard_queries/_editors.py:57",
    "shopifyseo/dashboard_queries/_editors.py:87",
    "shopifyseo/dashboard_queries/_object_detail.py:100",
    "shopifyseo/dashboard_queries/_object_detail.py:110",
    "shopifyseo/dashboard_queries/_object_detail.py:135",
    "shopifyseo/dashboard_queries/_object_detail.py:140",
    "shopifyseo/dashboard_queries/_object_detail.py:149",
    "shopifyseo/dashboard_queries/_object_detail.py:166",
    "shopifyseo/dashboard_queries/_object_detail.py:194",
    "shopifyseo/dashboard_queries/_object_detail.py:31",
    "shopifyseo/dashboard_queries/_object_detail.py:46",
    "shopifyseo/dashboard_queries/_object_detail.py:60",
    "shopifyseo/dashboard_queries/_object_detail.py:79",
    "shopifyseo/dashboard_queries/_object_detail.py:87",
    "shopifyseo/dashboard_queries/_object_detail.py:92",
    "shopifyseo/dashboard_queries/_object_detail.py:96",
    "shopifyseo/dashboard_queries/_seo_facts.py:157",
    "shopifyseo/dashboard_queries/_seo_facts.py:173",
    "shopifyseo/dashboard_queries/_text_tokens.py:144",
    "shopifyseo/dashboard_queries/_text_tokens.py:170",
    "shopifyseo/dashboard_queries/_text_tokens.py:215",
    "shopifyseo/dashboard_queries/_text_tokens.py:224",
    "shopifyseo/dashboard_queries/_urls.py:170",
    "shopifyseo/dashboard_queries/_urls.py:178",
    "shopifyseo/dashboard_queries/_urls.py:185",
    "shopifyseo/dashboard_queries/_urls.py:192",
    "shopifyseo/dashboard_store.py:1040",
    "shopifyseo/dashboard_store.py:1131",
    "shopifyseo/dashboard_store.py:117",
    "shopifyseo/dashboard_store.py:1195",
    "shopifyseo/dashboard_store.py:120",
    "shopifyseo/dashboard_store.py:1252",
    "shopifyseo/dashboard_store.py:1264",
    "shopifyseo/dashboard_store.py:1302",
    "shopifyseo/dashboard_store.py:1343",
    "shopifyseo/dashboard_store.py:1401",
    "shopifyseo/dashboard_store.py:1413",
    "shopifyseo/dashboard_store.py:143",
    "shopifyseo/dashboard_store.py:1440",
    "shopifyseo/dashboard_store.py:1495",
    "shopifyseo/dashboard_store.py:1528",
    "shopifyseo/dashboard_store.py:159",
    "shopifyseo/dashboard_store.py:1599",
    "shopifyseo/dashboard_store.py:162",
    "shopifyseo/dashboard_store.py:1648",
    "shopifyseo/dashboard_store.py:175",
    "shopifyseo/dashboard_store.py:1774",
    "shopifyseo/dashboard_store.py:1788",
    "shopifyseo/dashboard_store.py:1830",
    "shopifyseo/dashboard_store.py:1871",
    "shopifyseo/dashboard_store.py:192",
    "shopifyseo/dashboard_store.py:1993",
    "shopifyseo/dashboard_store.py:1994",
    "shopifyseo/dashboard_store.py:1995",
    "shopifyseo/dashboard_store.py:2005",
    "shopifyseo/dashboard_store.py:204",
    "shopifyseo/dashboard_store.py:218",
    "shopifyseo/dashboard_store.py:227",
    "shopifyseo/dashboard_store.py:246",
    "shopifyseo/dashboard_store.py:274",
    "shopifyseo/dashboard_store.py:291",
    "shopifyseo/dashboard_store.py:309",
    "shopifyseo/dashboard_store.py:318",
    "shopifyseo/dashboard_store.py:334",
    "shopifyseo/dashboard_store.py:340",
    "shopifyseo/dashboard_store.py:373",
    "shopifyseo/dashboard_store.py:420",
    "shopifyseo/dashboard_store.py:436",
    "shopifyseo/dashboard_store.py:459",
    "shopifyseo/dashboard_store.py:463",
    "shopifyseo/dashboard_store.py:467",
    "shopifyseo/dashboard_store.py:471",
    "shopifyseo/dashboard_store.py:475",
    "shopifyseo/dashboard_store.py:509",
    "shopifyseo/dashboard_store.py:522",
    "shopifyseo/dashboard_store.py:533",
    "shopifyseo/dashboard_store.py:550",
    "shopifyseo/dashboard_store.py:616",
    "shopifyseo/dashboard_store.py:630",
    "shopifyseo/dashboard_store.py:656",
    "shopifyseo/dashboard_store.py:671",
    "shopifyseo/dashboard_store.py:682",
    "shopifyseo/dashboard_store.py:698",
    "shopifyseo/dashboard_store.py:701",
    "shopifyseo/dashboard_store.py:717",
    "shopifyseo/dashboard_store.py:720",
    "shopifyseo/dashboard_store.py:734",
    "shopifyseo/dashboard_store.py:739",
    "shopifyseo/dashboard_store.py:75",
    "shopifyseo/dashboard_store.py:765",
    "shopifyseo/dashboard_store.py:769",
    "shopifyseo/dashboard_store.py:787",
    "shopifyseo/dashboard_store.py:79",
    "shopifyseo/dashboard_store.py:790",
    "shopifyseo/dashboard_store.py:87",
    "shopifyseo/dashboard_store.py:928",
    "shopifyseo/dashboard_store.py:999",
    # =========================================================================
    # shopifyseo/db/ - Database layer internals (OK to use direct execute)
    # =========================================================================
    "shopifyseo/db/connect.py:26",
    "shopifyseo/db/connect.py:28",
    "shopifyseo/db/connect.py:29",
    "shopifyseo/db/helpers.py:104",
    "shopifyseo/db/helpers.py:118",
    "shopifyseo/db/helpers.py:122",
    "shopifyseo/db/helpers.py:145",
    "shopifyseo/db/helpers.py:157",
    "shopifyseo/db/helpers.py:162",
    "shopifyseo/db/helpers.py:180",
    "shopifyseo/db/helpers.py:195",
    "shopifyseo/db/helpers.py:208",
    "shopifyseo/db/helpers.py:211",
    "shopifyseo/db/helpers.py:225",
    "shopifyseo/db/helpers.py:237",
    "shopifyseo/db/helpers.py:33",
    "shopifyseo/db/helpers.py:37",
    "shopifyseo/db/helpers.py:59",
    "shopifyseo/db/helpers.py:62",
    "shopifyseo/db/helpers.py:64",
    "shopifyseo/db/helpers.py:74",
    "shopifyseo/db/helpers.py:80",
    "shopifyseo/db/helpers.py:93",
    "shopifyseo/db/helpers.py:97",
    "shopifyseo/db/identity.py:126",
    "shopifyseo/db/identity.py:91",
    # =========================================================================
    # shopifyseo/ - Remaining modules (PR4+)
    # =========================================================================
    "shopifyseo/embedding_store.py:1031",
    "shopifyseo/embedding_store.py:1061",
    "shopifyseo/embedding_store.py:1081",
    "shopifyseo/embedding_store.py:1125",
    "shopifyseo/embedding_store.py:1147",
    "shopifyseo/embedding_store.py:1209",
    "shopifyseo/embedding_store.py:1263",
    "shopifyseo/embedding_store.py:1306",
    "shopifyseo/embedding_store.py:1314",
    "shopifyseo/embedding_store.py:1319",
    "shopifyseo/embedding_store.py:1324",
    "shopifyseo/embedding_store.py:1329",
    "shopifyseo/embedding_store.py:1334",
    "shopifyseo/embedding_store.py:1349",
    "shopifyseo/embedding_store.py:1356",
    "shopifyseo/embedding_store.py:1397",
    "shopifyseo/embedding_store.py:1416",
    "shopifyseo/embedding_store.py:1447",
    "shopifyseo/embedding_store.py:1473",
    "shopifyseo/embedding_store.py:175",
    "shopifyseo/embedding_store.py:211",
    "shopifyseo/embedding_store.py:280",
    "shopifyseo/embedding_store.py:293",
    "shopifyseo/embedding_store.py:295",
    "shopifyseo/embedding_store.py:297",
    "shopifyseo/embedding_store.py:301",
    "shopifyseo/embedding_store.py:315",
    "shopifyseo/embedding_store.py:576",
    "shopifyseo/embedding_store.py:579",
    "shopifyseo/embedding_store.py:582",
    "shopifyseo/embedding_store.py:585",
    "shopifyseo/embedding_store.py:588",
    "shopifyseo/embedding_store.py:591",
    "shopifyseo/embedding_store.py:596",
    "shopifyseo/embedding_store.py:601",
    "shopifyseo/embedding_store.py:606",
    "shopifyseo/embedding_store.py:634",
    "shopifyseo/embedding_store.py:641",
    "shopifyseo/embedding_store.py:648",
    "shopifyseo/embedding_store.py:655",
    "shopifyseo/embedding_store.py:662",
    "shopifyseo/embedding_store.py:669",
    "shopifyseo/embedding_store.py:676",
    "shopifyseo/embedding_store.py:680",
    "shopifyseo/embedding_store.py:691",
    "shopifyseo/embedding_store.py:763",
    "shopifyseo/embedding_store.py:810",
    "shopifyseo/embedding_store.py:876",
    "shopifyseo/embedding_store.py:937",
    "shopifyseo/embedding_store.py:942",
    "shopifyseo/embedding_sync.py:227",
    "shopifyseo/index_evidence.py:160",
    "shopifyseo/index_evidence.py:164",
    "shopifyseo/index_evidence.py:166",
    "shopifyseo/index_evidence.py:178",
    "shopifyseo/index_evidence.py:188",
    "shopifyseo/index_evidence.py:190",
    "shopifyseo/index_evidence.py:233",
    "shopifyseo/index_evidence.py:247",
    "shopifyseo/index_evidence.py:272",
    "shopifyseo/index_evidence.py:283",
    "shopifyseo/index_evidence.py:290",
    "shopifyseo/index_evidence.py:308",
    "shopifyseo/index_evidence.py:319",
    "shopifyseo/index_evidence.py:324",
    "shopifyseo/index_evidence.py:45",
    "shopifyseo/internal_links/ai_weave.py:106",
    "shopifyseo/internal_links/ai_weave.py:63",
    "shopifyseo/internal_links/ai_weave.py:68",
    "shopifyseo/internal_links/ai_weave.py:75",
    "shopifyseo/internal_links/apply.py:108",
    "shopifyseo/internal_links/apply.py:155",
    "shopifyseo/internal_links/apply.py:172",
    "shopifyseo/internal_links/apply.py:202",
    "shopifyseo/internal_links/apply.py:209",
    "shopifyseo/internal_links/apply.py:212",
    "shopifyseo/internal_links/apply.py:217",
    "shopifyseo/internal_links/apply.py:220",
    "shopifyseo/internal_links/apply.py:222",
    "shopifyseo/internal_links/apply.py:253",
    "shopifyseo/internal_links/apply.py:278",
    "shopifyseo/internal_links/apply.py:287",
    "shopifyseo/internal_links/apply.py:303",
    "shopifyseo/internal_links/apply.py:311",
    "shopifyseo/internal_links/apply.py:340",
    "shopifyseo/internal_links/apply.py:352",
    "shopifyseo/internal_links/apply.py:368",
    "shopifyseo/internal_links/apply.py:455",
    "shopifyseo/internal_links/apply.py:46",
    "shopifyseo/internal_links/apply.py:469",
    "shopifyseo/internal_links/apply.py:474",
    "shopifyseo/internal_links/apply.py:487",
    "shopifyseo/internal_links/apply.py:52",
    "shopifyseo/internal_links/apply.py:62",
    "shopifyseo/internal_links/apply.py:94",
    "shopifyseo/internal_links/auto_apply.py:116",
    "shopifyseo/internal_links/auto_apply.py:191",
    "shopifyseo/internal_links/auto_apply.py:73",
    "shopifyseo/internal_links/graph.py:75",
    "shopifyseo/internal_links/graph.py:78",
    "shopifyseo/internal_links/graph.py:87",
    "shopifyseo/internal_links/graph.py:95",
    "shopifyseo/internal_links/manual_weave.py:241",
    "shopifyseo/internal_links/manual_weave.py:248",
    "shopifyseo/internal_links/manual_weave.py:291",
    "shopifyseo/internal_links/manual_weave.py:352",
    "shopifyseo/internal_links/manual_weave.py:360",
    "shopifyseo/internal_links/manual_weave.py:403",
    "shopifyseo/internal_links/manual_weave.py:440",
    "shopifyseo/internal_links/pipeline.py:100",
    "shopifyseo/internal_links/pipeline.py:106",
    "shopifyseo/internal_links/pipeline.py:109",
    "shopifyseo/internal_links/pipeline.py:121",
    "shopifyseo/internal_links/pipeline.py:127",
    "shopifyseo/internal_links/pipeline.py:131",
    "shopifyseo/internal_links/pipeline.py:140",
    "shopifyseo/internal_links/pipeline.py:167",
    "shopifyseo/internal_links/pipeline.py:173",
    "shopifyseo/internal_links/pipeline.py:179",
    "shopifyseo/internal_links/pipeline.py:187",
    "shopifyseo/internal_links/pipeline.py:194",
    "shopifyseo/internal_links/pipeline.py:201",
    "shopifyseo/internal_links/pipeline.py:229",
    "shopifyseo/internal_links/pipeline.py:237",
    "shopifyseo/internal_links/pipeline.py:244",
    "shopifyseo/internal_links/pipeline.py:265",
    "shopifyseo/internal_links/pipeline.py:306",
    "shopifyseo/internal_links/pipeline.py:321",
    "shopifyseo/internal_links/pipeline.py:329",
    "shopifyseo/internal_links/pipeline.py:337",
    "shopifyseo/internal_links/pipeline.py:346",
    "shopifyseo/internal_links/pipeline.py:357",
    "shopifyseo/internal_links/pipeline.py:407",
    "shopifyseo/internal_links/safety.py:357",
    "shopifyseo/internal_links/store.py:10",
    "shopifyseo/internal_links/store.py:24",
    "shopifyseo/internal_links/store.py:27",
    "shopifyseo/internal_links/store.py:31",
    "shopifyseo/internal_links/store.py:38",
    "shopifyseo/internal_links/store.py:5",
    "shopifyseo/internal_links/store.py:7",
    "shopifyseo/internal_links/store.py:9",
    "shopifyseo/internal_links/write_time.py:107",
    "shopifyseo/internal_links/write_time.py:112",
    "shopifyseo/internal_links/write_time.py:117",
    "shopifyseo/internal_links/write_time.py:120",
    "shopifyseo/opportunity_tasks.py:10",
    "shopifyseo/opportunity_tasks.py:112",
    "shopifyseo/opportunity_tasks.py:118",
    "shopifyseo/opportunity_tasks.py:122",
    "shopifyseo/opportunity_tasks.py:123",
    "shopifyseo/opportunity_tasks.py:130",
    "shopifyseo/opportunity_tasks.py:136",
    "shopifyseo/opportunity_tasks.py:17",
    "shopifyseo/opportunity_tasks.py:32",
    "shopifyseo/opportunity_tasks.py:40",
    "shopifyseo/opportunity_tasks.py:43",
    "shopifyseo/opportunity_tasks.py:51",
    "shopifyseo/opportunity_tasks.py:59",
    "shopifyseo/opportunity_tasks.py:62",
    "shopifyseo/opportunity_tasks.py:69",
    "shopifyseo/opportunity_tasks.py:93",
    "shopifyseo/opportunity_tasks.py:97",
    "shopifyseo/product_linkability.py:103",
    "shopifyseo/product_linkability.py:116",
    "shopifyseo/product_linkability.py:133",
    "shopifyseo/product_linkability.py:40",
    "shopifyseo/rank_tracking/store.py:11",
    "shopifyseo/rank_tracking/store.py:52",
    "shopifyseo/rank_tracking/store.py:55",
    "shopifyseo/rank_tracking/store.py:58",
    "shopifyseo/rank_tracking/store.py:62",
    "shopifyseo/rank_tracking/store.py:67",
    "shopifyseo/rank_tracking/store.py:68",
    "shopifyseo/rank_tracking/store.py:72",
    "shopifyseo/rank_tracking/store.py:74",
    "shopifyseo/rank_tracking/store.py:75",
    "shopifyseo/rank_tracking/store.py:76",
    "shopifyseo/shopify_catalog_sync/__init__.py:100",
    "shopifyseo/shopify_catalog_sync/__init__.py:101",
    "shopifyseo/shopify_catalog_sync/__init__.py:102",
    "shopifyseo/shopify_catalog_sync/__init__.py:103",
    "shopifyseo/shopify_catalog_sync/__init__.py:105",
    "shopifyseo/shopify_catalog_sync/__init__.py:94",
    "shopifyseo/shopify_catalog_sync/__init__.py:95",
    "shopifyseo/shopify_catalog_sync/__init__.py:96",
    "shopifyseo/shopify_catalog_sync/__init__.py:97",
    "shopifyseo/shopify_catalog_sync/__init__.py:98",
    "shopifyseo/shopify_catalog_sync/__init__.py:99",
    "shopifyseo/shopify_catalog_sync/blogs.py:139",
    "shopifyseo/shopify_catalog_sync/blogs.py:20",
    "shopifyseo/shopify_catalog_sync/blogs.py:25",
    "shopifyseo/shopify_catalog_sync/blogs.py:28",
    "shopifyseo/shopify_catalog_sync/blogs.py:32",
    "shopifyseo/shopify_catalog_sync/blogs.py:36",
    "shopifyseo/shopify_catalog_sync/blogs.py:40",
    "shopifyseo/shopify_catalog_sync/blogs.py:44",
    "shopifyseo/shopify_catalog_sync/blogs.py:48",
    "shopifyseo/shopify_catalog_sync/blogs.py:52",
    "shopifyseo/shopify_catalog_sync/blogs.py:56",
    "shopifyseo/shopify_catalog_sync/blogs.py:60",
    "shopifyseo/shopify_catalog_sync/blogs.py:65",
    "shopifyseo/shopify_catalog_sync/collections.py:112",
    "shopifyseo/shopify_catalog_sync/collections.py:198",
    "shopifyseo/shopify_catalog_sync/collections.py:278",
    "shopifyseo/shopify_catalog_sync/collections.py:30",
    "shopifyseo/shopify_catalog_sync/collections.py:40",
    "shopifyseo/shopify_catalog_sync/collections.py:45",
    "shopifyseo/shopify_catalog_sync/collections.py:53",
    "shopifyseo/shopify_catalog_sync/collections.py:62",
    "shopifyseo/shopify_catalog_sync/collections.py:68",
    "shopifyseo/shopify_catalog_sync/db.py:149",
    "shopifyseo/shopify_catalog_sync/db.py:157",
    "shopifyseo/shopify_catalog_sync/db.py:181",
    "shopifyseo/shopify_catalog_sync/db.py:183",
    "shopifyseo/shopify_catalog_sync/db.py:187",
    "shopifyseo/shopify_catalog_sync/db.py:460",
    "shopifyseo/shopify_catalog_sync/db.py:462",
    "shopifyseo/shopify_catalog_sync/db.py:463",
    "shopifyseo/shopify_catalog_sync/db.py:468",
    "shopifyseo/shopify_catalog_sync/db.py:481",
    "shopifyseo/shopify_catalog_sync/db.py:509",
    "shopifyseo/shopify_catalog_sync/db.py:97",
    "shopifyseo/shopify_catalog_sync/page_template_enrichment.py:30",
    "shopifyseo/shopify_catalog_sync/page_template_enrichment.py:41",
    "shopifyseo/shopify_catalog_sync/pages.py:23",
    "shopifyseo/shopify_catalog_sync/products.py:22",
    "shopifyseo/shopify_catalog_sync/products.py:238",
    "shopifyseo/shopify_catalog_sync/products.py:283",
    "shopifyseo/shopify_catalog_sync/products.py:314",
    "shopifyseo/shopify_catalog_sync/products.py:58",
    "shopifyseo/shopify_catalog_sync/products.py:63",
    "shopifyseo/shopify_catalog_sync/products.py:67",
    "shopifyseo/shopify_catalog_sync/products.py:71",
    "shopifyseo/shopify_catalog_sync/products.py:75",
    "shopifyseo/shopify_catalog_sync/products.py:79",
    "shopifyseo/shopify_catalog_sync/products.py:98",
    "shopifyseo/shopify_image_cache.py:285",
    "shopifyseo/shopify_image_cache.py:292",
    "shopifyseo/shopify_image_cache.py:298",
    "shopifyseo/shopify_image_cache.py:305",
    "shopifyseo/shopify_image_cache.py:366",
    "shopifyseo/shopify_image_cache.py:372",
    "shopifyseo/shopify_image_cache.py:377",
    "shopifyseo/shopify_image_cache.py:382",
    "shopifyseo/shopify_image_cache.py:395",
    "shopifyseo/shopify_image_cache.py:427",
    "shopifyseo/shopify_image_cache.py:433",
    "shopifyseo/shopify_image_cache.py:48",
    "shopifyseo/shopify_image_cache.py:497",
    "shopifyseo/shopify_image_cache.py:518",
}


EXCLUDED_DIRS = {
    "tests",
    "scripts",
    ".venv",
    "node_modules",
    "__pycache__",
    ".git",
    "frontend",
    "docs",
}


def _find_direct_execute_sites() -> set[str]:
    """Find all conn.execute( and similar patterns in the codebase."""
    workspace = Path(__file__).parent.parent
    sites: set[str] = set()

    pattern = re.compile(
        r'\b(?:conn|cursor|c|connection)\.execute(?:many|script)?\s*\(',
        re.IGNORECASE
    )

    comment_pattern = re.compile(r'^\s*#')

    for py_file in workspace.rglob("*.py"):
        rel_path = py_file.relative_to(workspace)

        if any(part in EXCLUDED_DIRS for part in rel_path.parts):
            continue

        if rel_path.name == "execute.py" and "db" in str(rel_path):
            continue

        try:
            content = py_file.read_text(encoding="utf-8")
        except Exception:
            continue

        for line_num, line in enumerate(content.splitlines(), start=1):
            if comment_pattern.match(line):
                continue

            if pattern.search(line):
                site = f"{rel_path}:{line_num}"
                sites.add(site)

    return sites


def test_no_new_direct_execute_sites():
    """Fail if there are direct execute sites not in the allowlist."""
    current_sites = _find_direct_execute_sites()
    new_sites = current_sites - ALLOWED_DIRECT_EXECUTE_SITES

    if new_sites:
        new_list = "\n  ".join(sorted(new_sites))
        pytest.fail(
            f"Found {len(new_sites)} new direct execute site(s) not in allowlist:\n  {new_list}\n\n"
            "Use shopifyseo.db.execute() instead of conn.execute() for proper "
            "PostgreSQL % escaping. If this is intentional, add to ALLOWED_DIRECT_EXECUTE_SITES."
        )


def test_allowlist_shrinkage_info():
    """Report entries that can be removed (code migrated/deleted)."""
    current_sites = _find_direct_execute_sites()
    stale_entries = ALLOWED_DIRECT_EXECUTE_SITES - current_sites

    if stale_entries:
        print(f"\n[INFO] {len(stale_entries)} allowlist entries can be removed:")
        for entry in sorted(stale_entries)[:10]:
            print(f"  {entry}")
        if len(stale_entries) > 10:
            print(f"  ... and {len(stale_entries) - 10} more")


def test_report_migration_progress():
    """Report the allowlist count for tracking migration progress."""
    current_sites = _find_direct_execute_sites()
    print(f"\n[MIGRATION PROGRESS]")
    print(f"  Allowlist baseline: 740 sites")
    print(f"  Current direct sites: {len(current_sites)}")
    print(f"  Allowlist entries: {len(ALLOWED_DIRECT_EXECUTE_SITES)}")
