"""Identity column helpers for PostgreSQL migration.

SQLite's INTEGER PRIMARY KEY columns get rowid auto-increment automatically.
PostgreSQL requires explicit GENERATED BY DEFAULT AS IDENTITY or SERIAL.

After bulk loads (e.g., via pgloader), Postgres sequences need to be reset
to max(id)+1 to avoid duplicate key errors on subsequent inserts.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from .backend import Backend, get_backend


@dataclass
class ResyncResult:
    """Result of resyncing a sequence."""

    table: str
    column: str
    new_value: int | None = None
    error: str | None = None


def identity_ddl(table: str, column: str = "id") -> str:
    """Generate PostgreSQL DDL for an identity column.

    Returns the column definition portion, e.g.:
    'id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY'

    This uses GENERATED BY DEFAULT (not ALWAYS) so that explicit id values
    can still be inserted during migrations/imports.
    Uses BIGINT to match pgloader default for INTEGER PRIMARY KEY.
    """
    return f"{column} BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"


def serial_ddl(table: str, column: str = "id") -> str:
    """Generate PostgreSQL DDL using SERIAL (older style).

    Returns: 'id SERIAL PRIMARY KEY'

    SERIAL is syntactic sugar for:
    - INTEGER NOT NULL
    - DEFAULT nextval('table_column_seq')
    - Creates sequence automatically
    """
    return f"{column} SERIAL PRIMARY KEY"


def get_sequence_name(
    conn: Any, table: str, column: str = "id", *, backend: Backend | None = None
) -> str | None:
    """Get the sequence name for a column using pg_get_serial_sequence.

    Returns the fully qualified sequence name, or None if no sequence exists.
    This properly handles both SERIAL and IDENTITY columns.
    Uses quote_ident() so reserved-word table names resolve correctly.
    """
    if backend is None:
        backend = get_backend()

    if backend != Backend.POSTGRES:
        return None

    from psycopg import sql

    query = sql.SQL("SELECT pg_get_serial_sequence(quote_ident({table}), {column})").format(
        table=sql.Literal(table), column=sql.Literal(column)
    )
    row = conn.execute(query).fetchone()
    return row[0] if row and row[0] else None


def _discover_identity_tables(conn: Any) -> list[tuple[str, str]]:
    """Discover tables with single-column integer primary keys.

    Returns list of (table_name, pk_column) tuples.
    Skips composite primary keys (e.g. cluster_keywords (cluster_id, keyword))
    by counting every PK column before filtering on integer types.
    Only considers regular tables in the current schema.
    """
    query = """
    WITH pk_cols AS (
        SELECT
            c.oid,
            c.relname AS table_name,
            a.attname AS column_name,
            format_type(a.atttypid, a.atttypmod) AS dtype
        FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        JOIN pg_index i ON i.indrelid = c.oid AND i.indisprimary
        JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum = ANY(i.indkey)
        WHERE c.relkind = 'r'
          AND n.nspname = current_schema()
    ),
    pk_counts AS (
        SELECT oid, COUNT(*) AS pk_col_count
        FROM pk_cols
        GROUP BY oid
    )
    SELECT p.table_name, p.column_name
    FROM pk_cols p
    JOIN pk_counts c ON c.oid = p.oid
    WHERE c.pk_col_count = 1
      AND p.dtype IN ('integer', 'bigint', 'smallint', 'int4', 'int8', 'int2')
    ORDER BY p.table_name
    """
    rows = conn.execute(query).fetchall()
    return [(row[0], row[1]) for row in rows]


def resync_sequence(
    conn: Any,
    table: str,
    column: str = "id",
    *,
    backend: Backend | None = None,
) -> ResyncResult:
    """Resync a PostgreSQL sequence to max(column)+1 after bulk load.

    This is essential after using pgloader or COPY to import data with
    explicit id values, as the sequence won't know about those values.

    On SQLite: No-op, returns result with new_value=None.
    On PostgreSQL: Finds sequence via pg_get_serial_sequence, executes setval,
    and returns the new sequence value. Uses ``conn.transaction()`` (a nested
    savepoint when already in a transaction) so this works on autocommit
    connections and does not abort the outer transaction on error.

    Args:
        conn: Database connection
        table: Table name
        column: Identity column name (default 'id')
        backend: Override backend detection

    Returns:
        ResyncResult with new_value on success or error message on failure
    """
    if backend is None:
        backend = get_backend()

    if backend != Backend.POSTGRES:
        return ResyncResult(table=table, column=column)

    from psycopg import sql

    try:
        with conn.transaction():
            seq_name = get_sequence_name(conn, table, column, backend=backend)
            if not seq_name:
                return ResyncResult(
                    table=table, column=column, error=f"No sequence found for {table}.{column}"
                )

            query = sql.SQL(
                "SELECT setval({seq}, COALESCE((SELECT MAX({col}) FROM {tbl}), 0) + 1, false)"
            ).format(
                seq=sql.Literal(seq_name),
                col=sql.Identifier(column),
                tbl=sql.Identifier(table),
            )
            row = conn.execute(query).fetchone()
            new_val = row[0] if row else None
            return ResyncResult(table=table, column=column, new_value=new_val)
    except Exception as e:
        return ResyncResult(table=table, column=column, error=str(e))


def resync_all_sequences(
    conn: Any,
    tables: list[tuple[str, str]] | None = None,
    *,
    backend: Backend | None = None,
) -> list[ResyncResult]:
    """Resync all identity sequences, discovering tables from the catalog.

    Args:
        conn: Database connection
        tables: Optional list of (table, column) tuples. If None, discovers
                tables with single-column integer PKs from the catalog.
        backend: Override backend detection

    Returns:
        List of ResyncResult for each table (includes errors)
    """
    if backend is None:
        backend = get_backend()

    if backend != Backend.POSTGRES:
        return []

    if tables is None:
        tables = _discover_identity_tables(conn)

    results = []
    for table, column in tables:
        result = resync_sequence(conn, table, column, backend=backend)
        results.append(result)

    return results


def ensure_identity(
    conn: Any,
    table: str,
    column: str = "id",
    *,
    backend: Backend | None = None,
) -> ResyncResult:
    """Ensure a column has an identity/sequence and resync it.

    For PK columns that have no default/sequence after pgloader migration,
    this adds GENERATED BY DEFAULT AS IDENTITY and resyncs the sequence.

    This is idempotent - if the column already has identity, only resyncs.
    Uses ``conn.transaction()`` so this works on autocommit connections.

    Args:
        conn: Database connection
        table: Table name
        column: Column name (default 'id')
        backend: Override backend detection

    Returns:
        ResyncResult with new_value on success or error message on failure
    """
    if backend is None:
        backend = get_backend()

    if backend != Backend.POSTGRES:
        return ResyncResult(table=table, column=column)

    from psycopg import sql

    try:
        with conn.transaction():
            existing_seq = get_sequence_name(conn, table, column, backend=backend)
            if not existing_seq:
                alter_query = sql.SQL(
                    "ALTER TABLE {tbl} ALTER COLUMN {col} ADD GENERATED BY DEFAULT AS IDENTITY"
                ).format(tbl=sql.Identifier(table), col=sql.Identifier(column))
                conn.execute(alter_query)
        return resync_sequence(conn, table, column, backend=backend)
    except Exception as e:
        return ResyncResult(table=table, column=column, error=str(e))


def create_identity_column_ddl(
    table: str,
    column: str = "id",
    *,
    backend: Backend | None = None,
) -> str:
    """Get the DDL fragment for an auto-increment primary key column.

    On SQLite: Returns 'column INTEGER PRIMARY KEY' (uses rowid alias)
    On PostgreSQL: Returns 'column BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY'
    """
    if backend is None:
        backend = get_backend()

    if backend == Backend.POSTGRES:
        return identity_ddl(table, column)
    else:
        return f"{column} INTEGER PRIMARY KEY"


# INTEGER PRIMARY KEY tables that need GENERATED BY DEFAULT AS IDENTITY on
# Postgres after a bulk load (pgloader). Used by the later data-migration PR.
#
# seo_change_events.task_id must NOT get identity: it is a 1:1 primary key
# equal to seo_opportunity_tasks.id (INSERT copies the task id), not an
# independent sequence.
IDENTITY_COLUMNS: dict[str, str] = {
    "rank_checks": "id",
    "rank_requests": "id",
    "robots_snapshots": "id",
    "seo_opportunity_tasks": "id",
    "tracked_keywords": "id",
}
