"""Identity column helpers for PostgreSQL migration.

SQLite's INTEGER PRIMARY KEY columns get rowid auto-increment automatically.
PostgreSQL requires explicit GENERATED BY DEFAULT AS IDENTITY or SERIAL.

After bulk loads (e.g., via pgloader), Postgres sequences need to be reset
to max(id)+1 to avoid duplicate key errors on subsequent inserts.
"""
from __future__ import annotations

from typing import Any

from .backend import Backend, get_backend


IDENTITY_COLUMNS: dict[str, str] = {
    "team_tasks": "id",
    "team_task_events": "id",
    "clusters": "id",
    "cluster_keywords": "id",
    "seo_opportunity_tasks": "id",
    "link_suggestions": "id",
}


def identity_ddl(table: str, column: str = "id") -> str:
    """Generate PostgreSQL DDL for an identity column.

    Returns the column definition portion, e.g.:
    'id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY'

    This uses GENERATED BY DEFAULT (not ALWAYS) so that explicit id values
    can still be inserted during migrations/imports.
    """
    return f"{column} INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"


def serial_ddl(table: str, column: str = "id") -> str:
    """Generate PostgreSQL DDL using SERIAL (older style).

    Returns: 'id SERIAL PRIMARY KEY'

    SERIAL is syntactic sugar for:
    - INTEGER NOT NULL
    - DEFAULT nextval('table_column_seq')
    - Creates sequence automatically
    """
    return f"{column} SERIAL PRIMARY KEY"


def get_sequence_name(table: str, column: str = "id") -> str:
    """Get the expected sequence name for an identity/serial column.

    PostgreSQL naming convention: {table}_{column}_seq
    """
    return f"{table}_{column}_seq"


def resync_sequence(
    conn: Any,
    table: str,
    column: str = "id",
    *,
    backend: Backend | None = None,
) -> int | None:
    """Resync a PostgreSQL sequence to max(column)+1 after bulk load.

    This is essential after using pgloader or COPY to import data with
    explicit id values, as the sequence won't know about those values.

    On SQLite: No-op, returns None (SQLite doesn't have sequences).
    On PostgreSQL: Executes setval() and returns the new sequence value.

    Args:
        conn: Database connection
        table: Table name
        column: Identity column name (default 'id')
        backend: Override backend detection

    Returns:
        New sequence value on PostgreSQL, None on SQLite
    """
    if backend is None:
        backend = get_backend()

    if backend != Backend.POSTGRES:
        return None

    seq_name = get_sequence_name(table, column)

    row = conn.execute(
        f"SELECT setval(%s, COALESCE((SELECT MAX({column}) FROM {table}), 0) + 1, false)",
        (seq_name,),
    ).fetchone()
    return row[0] if row else None


def resync_all_sequences(
    conn: Any,
    tables: dict[str, str] | None = None,
    *,
    backend: Backend | None = None,
) -> dict[str, int]:
    """Resync all identity sequences in the known tables.

    Args:
        conn: Database connection
        tables: Dict of {table: column} to resync. Defaults to IDENTITY_COLUMNS.
        backend: Override backend detection

    Returns:
        Dict of {table: new_sequence_value} for each successfully resynced table
    """
    if backend is None:
        backend = get_backend()

    if backend != Backend.POSTGRES:
        return {}

    if tables is None:
        tables = IDENTITY_COLUMNS

    results = {}
    for table, column in tables.items():
        try:
            row = conn.execute(
                "SELECT to_regclass(%s) IS NOT NULL", (table,)
            ).fetchone()
            if row and row[0]:
                new_val = resync_sequence(conn, table, column, backend=backend)
                if new_val is not None:
                    results[table] = new_val
        except Exception:
            pass
    return results


def create_identity_column_ddl(
    table: str,
    column: str = "id",
    *,
    backend: Backend | None = None,
) -> str:
    """Get the DDL fragment for an auto-increment primary key column.

    On SQLite: Returns 'column INTEGER PRIMARY KEY' (uses rowid alias)
    On PostgreSQL: Returns 'column INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY'
    """
    if backend is None:
        backend = get_backend()

    if backend == Backend.POSTGRES:
        return identity_ddl(table, column)
    else:
        return f"{column} INTEGER PRIMARY KEY"
